### ISSUE TITLE
As a socialworker I should be able to get an overview of what happened previously in a specific process. Version 1 (8)

### ISSUE THREAD

**Issue by mortenmarquard** [DCRGraphsNet/DCROpenCaseManager#25]
Lower left corner of mockup from Henrik Nielsen 13/2-2019
Leverance: Mockup + implementation i OCM instans side

Original tekst:
Socialrådgiveren skal let kunne få et overblik over hvad der tidligere er sket i den konkrete indsats first version

**Comment by HenrikWNielsen** [comment]
Ting de skal kunne se: 
- Sidste opfølgningsdato
- Dato for opstartsmøde
- Modtage Ansøgninger (Dato for aktivitet)
- Næste opfølgningsdato
- Bevilling start dato
- Bevilling stop dato
- Diagnose (tekstfelt)
- Egne notater (tekstfelt)
- Opgaver/kommende aktiviteter
- Sidste udredningsdato fra BUC (BUA)
Generelt:  Tidslinje (notat, dokument, børnesamtale, opfølgningsdato)
