### ISSUE TITLE
Timeline mockup

### ISSUE THREAD

**Issue by ThaisCorneliussen** [DCRGraphsNet/DCROpenCaseManager#32]
- [x] Brainstorming

- [x] Sketching

- [x] Wireframing

**Comment by ThaisCorneliussen** [comment]
![billede](https://user-images.githubusercontent.com/47529973/53485137-bbf57d80-3a85-11e9-9068-f5b43002afde.png)

**Comment by ThaisCorneliussen** [comment]
![billede](https://user-images.githubusercontent.com/47529973/53485166-cd3e8a00-3a85-11e9-9044-a363d56d7119.png)

**Comment by ThaisCorneliussen** [comment]
![billede](https://user-images.githubusercontent.com/47529973/53485281-17277000-3a86-11e9-8aa2-ec6d086f4d23.png)

**Comment by lauralunddahl** [comment]
![billede](https://user-images.githubusercontent.com/47529980/53867816-e77fe700-3ff4-11e9-9b1c-af5c5159ef6b.png)
