### ISSUE TITLE
Stamdata mockup

### ISSUE THREAD

**Issue by NannaMarcher** [DCRGraphsNet/DCROpenCaseManager#33]
- [x] Brainstorming

- [x] Sketching

- [x] Wireframing

**Comment by ThaisCorneliussen** [comment]
![billede](https://user-images.githubusercontent.com/47529973/53485194-e5160e00-3a85-11e9-98dc-c1d850f3836e.png)

**Comment by ThaisCorneliussen** [comment]
![billede](https://user-images.githubusercontent.com/47529973/53485216-f19a6680-3a85-11e9-84b4-a8317dfd29e0.png)

**Comment by lauralunddahl** [comment]
![billede](https://user-images.githubusercontent.com/47529980/53867851-febed480-3ff4-11e9-878f-95da662c3da0.png)
