### ISSUE TITLE
Som socialrådgiver ønsker jeg at, jeg kan se hvis en søskende har en aktivsag eller lukket sag.

### ISSUE THREAD

**Issue by NicklasHealySyddjurs** [DCRGraphsNet/DCROpenCaseManager#345]
Måske et ikon i Webpart Context, i forlængelse med "Stamdata" med forskellige farver ift. om der er:                
•	En aktiv sag
•	En afsluttet sag
•	Ingen sag

**Comment by DCRGraphs** [comment]
Tænker det kan løses i "context" web part'e til højre på siden - hvor der vises information om familien. Man søger samtidig i Acadre efter om der er en aktiv børnesag på barnet - og viser da et link hvis det er tilfældet.

David skal lave logik som returnerer disse inforamtioner - udover søskende også link til evt Acadre børnesamlesag - og link til den. Vi åbner så  OCM baseret på dette link.

**Comment by NicklasHealySyddjurs** [comment]
jeg tænker der skal søges efter om der er en "Løbende Journal" sag, hvis der er det, skal rådgiver kunne se det umiddelbart uden at udvide "Context".

Vedr. linket, vil det ikke være bedre hvis OCM fik "Case ID" på søskendes journalsage?
Dette skal bare sammensættes i et link.

**Comment by NicklasHealySyddjurs** [comment]
Har været i dialog med nogle rådgiver, som vil anbefale at de får vist "Aktiv søskende sag" over teksten "OBS!".
Kommentar kan se på dette dokument
[Hvor skal Søskende vises.pptx](https://github.com/DCRGraphsNet/DCROpenCaseManager/files/3642341/Hvor.skal.Soskende.vises.pptx)

**Comment by DCRGraphs** [comment]
"Aktiv søskende sag" står i toppen af siden nu hvis der er en sag. Da der kan være flere søskende og sager må man gå ned til det enkelte barn.

**Comment by NicklasHealySyddjurs** [comment]
"Aktiv søskende sag" er ikke tydelig nok for sagsbehandleren.

**Comment by DCRGraphs** [comment]
Ok - hvordan skal det være mere tydeligt. Rødt? Bold? Ideer please.

**Comment by NicklasHealySyddjurs** [comment]
Vil det være muligt at lave den i samme farve som syddjurs logoet.
Og kan den adskildes lidt mere fra CPR?
![image](https://user-images.githubusercontent.com/47558591/67365928-d7f8e280-f572-11e9-8cf1-a711787476a3.png)

**Comment by DCRGraphs** [comment]
![image](https://user-images.githubusercontent.com/19911233/67499546-9571fb80-f681-11e9-92b1-ffe9fec7bee2.png)

**Comment by DCRGraphs** [comment]
Er dette ok?

**Comment by NicklasHealySyddjurs** [comment]
Det er rigtig fint.
