### ISSUE TITLE
Activities mockup

### ISSUE THREAD

**Issue by NannaMarcher** [DCRGraphsNet/DCROpenCaseManager#35]
- [x] Brainstorming

- [x] Sketching

- [x] Wireframing

**Comment by ThaisCorneliussen** [comment]
![billede](https://user-images.githubusercontent.com/47529973/53485306-2a3a4000-3a86-11e9-9b90-a0d0a57d0b89.png)

**Comment by lauralunddahl** [comment]
![img_1625](https://user-images.githubusercontent.com/47529980/53867645-92dc6c00-3ff4-11e9-9a79-2cca62c7d30f.jpg)

**Comment by lauralunddahl** [comment]
![img_1625](https://user-images.githubusercontent.com/47529980/53867708-b7d0df00-3ff4-11e9-8a6f-2319fd99022e.jpg)

**Comment by lauralunddahl** [comment]
![billede](https://user-images.githubusercontent.com/47529980/53867738-c8815500-3ff4-11e9-9dd2-b3e3a542be03.png)
