### ISSUE TITLE
As a social worker I want to  see the name on the process on the “journalnotat” if it is related. (2)

### ISSUE THREAD

**Issue by Scharling** [DCRGraphsNet/DCROpenCaseManager#87]
Hej @Scharling Kan du oplyse på hvilke siden denne funktion skal være gældende?

**Comment by NicklasHealySyddjurs** [comment]
Hej @Scharling 

Et journalnotat relater altid til en proces eller generelt.
Som socialrådgiver skal jeg have mulighed for at vælge om journalnotatet er relateret til en proces eller generelt.
